import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 - Royal Ember Theme
        'surface': '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1b1b1c',
        'surface-container': '#202020',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353535',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c7c7',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#303030',
        'outline': '#8e9192',
        'outline-variant': '#444748',
        'surface-tint': '#c8c6c5',
        'primary': '#c8c6c5',
        'on-primary': '#313030',
        'primary-container': '#121212',
        'on-primary-container': '#7e7d7d',
        'inverse-primary': '#5f5e5e',
        'secondary': '#e9c349',
        'on-secondary': '#3c2f00',
        'secondary-container': '#af8d11',
        'on-secondary-container': '#342800',
        'tertiary': '#c6c6c7',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#101213',
        'on-tertiary-container': '#7c7d7e',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#e5e2e1',
        'primary-fixed-dim': '#c8c6c5',
        'on-primary-fixed': '#1c1b1b',
        'on-primary-fixed-variant': '#474646',
        'secondary-fixed': '#ffe088',
        'secondary-fixed-dim': '#e9c349',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#574500',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        'background': '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353535',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'unit': '8px',
        'container-max': '1440px',
        'gutter': '32px',
        'margin-mobile': '24px',
        'margin-desktop': '80px',
        'section-padding': '160px',
      },
      fontFamily: {
        'display-xl': ['var(--font-noto-serif)', 'serif'],
        'headline-lg': ['var(--font-noto-serif)', 'serif'],
        'headline-md': ['var(--font-noto-serif)', 'serif'],
        'body-lg': ['var(--font-inter)', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'sans-serif'],
        'label-caps': ['var(--font-inter)', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['80px', { lineHeight: '1.1', fontWeight: '400', letterSpacing: '-0.02em' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '400', letterSpacing: '-0.01em' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '300', letterSpacing: '0.01em' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', fontWeight: '600', letterSpacing: '0.2em' }],
      },
      backdropFilter: {
        'none': 'none',
        'blur': 'blur(20px)',
      },
      boxShadow: {
        'glass': '0 8px 32px rgba(0, 0, 0, 0.3)',
        'glass-lg': '0 30px 60px rgba(0, 0, 0, 0.5)',
        'gold-glow': '0 0 20px rgba(233, 195, 73, 0.2)',
      },
      animation: {
        'bounce-slow': 'bounce 2s infinite',
        'fade-in': 'fadeIn 0.6s ease-in',
        'slide-up': 'slideUp 0.6s ease-out',
        'scale-in': 'scaleIn 0.4s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
      },
      container: {
        center: true,
        padding: {
          DEFAULT: '1rem',
          sm: '2rem',
          lg: '4rem',
          xl: '5rem',
          '2xl': '6rem',
        },
        maxWidth: {
          '2xl': '1440px',
        },
      },
    },
  },
  plugins: [],
};

export default config;
